title: Nisha's first Blog using Jekyll
author: Nish
email: myemail@somethng
description: > # this means to ignore newlines until "baseurl:"
  This is my blog's description.ta da!.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
