title: Nisha's first jekyll theme project
author: NS
email: Myemail@somedomain
description: > # this means to ignore newlines until "baseurl:"
  Hello There.. This is a very nice course on github.. 5* :)

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-leap-day
